GET http://localhost:5034/games

###

GET http://localhost:5034/games/3

###

POST http://localhost:5034/games
Content-Type: application/json

{
   "name": "Flight Simulator",
   "genreId": 5,
   "price": 89.99,
   "releaseDate": "2020-11-14"
}

###
PUT http://localhost:5034/games/3
Content-Type: application/json

{
  "name": "Forza Horizon 6",
   "genreId": 5,
   "price": 49.99,
   "releaseDate": "1999-11-14"
}

###

DELETE http://localhost:5034/games/2

###
GET http://localhost:5034/genres